spring.application.name=UnitedService

spring.datasource.url=jdbc:mysql://united-mysql:3306/service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=united
spring.datasource.password=unitedpass123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=admin
jwt.secret.key=O1sI8EBWYRWo7JKTJe9USgtw2JlNIeG5wxPDmYHOPlc=
jwt.expiration.time=5184000000

spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.globally_quoted_identifiers_skip_column_definitions=true

# File upload configuration
file.upload-dir=/app/uploads
file.upload-dir.photos=/app/uploads/photos
file.upload-dir.attachments=/app/uploads/attachments

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# Push Notification VAPID Keys
vapid.public.key=BJvnndHkawWKbjG7gm9K1GWg9VWhRfyDwzp4B5BkjhEqLw9OOPe5W5o81T8XrXLeZbjDAFIDOqIp403MAzKPNOU
vapid.private.key=ee0jOzngBI9Rj_SOr-sK1Fk4BLuwfO6UjyTq1FUuDFI
vapid.subject=mailto:contact.unitedservices@gmail.com

# Enable async
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100

app.base-url=http://51.38.49.98:4200